
image: Visual Studio 2017

branches:
  only:
    - master

clone_folder: c:\projects\HabService

environment:
  hab_exe_version: "%24latest"
  HAB_AUTH_TOKEN:
    secure: /deSCNJcZdHrtFNJ3zl4zgTjUs+AjT3MStKYbikPLa0anFOS7f4RydFV5cER/mamh5b2sDT2IVASK1uc5SRzE/LTNbcTvspontu9Kbu8to4LEyk4R/MGYpYRHImcVmKHo8zAs7lqp1zx7gJu+TLYi24RfWDQOu4M8WEX4CzFAtcLn2B21obLEehqp6vO6xUXDSTY3WeFfEoPfL3DUUo6BsWNgm68lvGcif6fGt/bw+g=
  ORIGIN_KEY:
    secure: T03FGJrevgQSlLfkc0mDaIkRyfu0/ci6+ryDnSqrezAmbtTayisHStac1yS4/96fMQmyfPYpGP5tMtvjuyw0cplUAUEtXarcK8CgatwnE+t7c9sjpBWgKfSE3wLOiDla

build_script:
  - ps: .\build.ps1

artifacts:
  - path: 'results\*.hart'
